### ISSUE TITLE
Default contrast mode looks washed out

### ISSUE THREAD

**Issue by bharadwaj-raju** [denysvitali/thebestmotherfuckingwebsite#18] opened 2017-12-23 09:14 UTC
As you asked me to on [the Reddit thread](https://www.reddit.com/r/linux/comments/7kzdlo/i_launched_a_website_around_computer_freedom/). (I'm /u/UniversallyUniqueID)

The default contrast option looks very washed out, especially if you compare it to [better-mf-website](http://bettermotherfuckingwebsite.com) and [original-mf-website](http://motherfuckingwebsite.com).

The colored text looks decent at default, though, and the red actually looks "burnt" at more contrast.

Thus, I'd like the default contrast to be as per "Add more contast", but the colored text to be kept as at default contrast.

**Comment by denysvitali** [comment] 2017-12-23 14:42
Thank you for your suggestion!  
In my opinion the [#151515](http://www.color-hex.com/color/151515) is too dark, but I agree with you, [#555](http://www.color-hex.com/color/555) is too washed out.  
I'll fix it by changing the text color to [#454545](http://www.color-hex.com/color/454545) and the background color to a [more white one](http://www.color-hex.com/color/fefefe). Hopefully it will fix the issue and improve readability, whilst maintaining a good design that doesn't look like the [first website ever published](http://info.cern.ch/hypertext/WWW/TheProject.html).

**Comment by denysvitali** [comment] 2017-12-23 14:47
Fixed in e632c8c, hopefully this will fix the issue. Feel free to reopen it / comment again if you think that the issue is still not solved.

**Closed by denysvitali** 2017-12-23 14:47 UTC
Labels: contrast, design, to-do

**Comment by bharadwaj-raju** [comment] 2017-12-23 16:24
Much better! Thank you.

Now the question arises: do we need the "Add more contrast" button now?

**Comment by denysvitali** [comment] 2017-12-26 15:17
I guess so. Everything that helps with readability should be included. We want to be as accessible as possible :)
